# Generated by Django 3.2.7 on 2024-04-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
